# Setup
title: あーるのシレン2 TA日記
tagline: 現在の最果てへの道99FTA自己ベスト 1時間4分20秒 (世界6位)
baseurl: "http://shiren2-speedrun.com"
paginate: 1
locale: "ja"
description: "このサイトは風来のシレン2 鬼襲来シレン城のTAに関することを書き連ねるブログです。"
keyword: 風来のシレン,風来のシレン2,シレン2,シレン２,RTA,TA,シレン64,最果てへの道,最果てへの道99FTA,あーる

links:
  youtube: "https://www.youtube.com/channel/UCaf0gShSdR6PeVqibl5TNJg"
  twitch: "https://www.twitch.tv/r_iwn"
  twitter: "https://twitter.com/r_sprl"
  niconico: "https://com.nicovideo.jp/community/co3363392"
  shiren2: "https://shiren2.herokuapp.com/"
  shiren2Discord: "https://discord.gg/6ftRftAmHV"

# About/contact
author:
  name: あーる
  url: https://www.youtube.com/channel/UCaf0gShSdR6PeVqibl5TNJg

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap

#パンくず
breadcrumbs:
  root:
    hide: true
    image: true

#Others
markdown: kramdown

theme: jekyll-theme-cayman
google_analytics: G-NJP9Z3ZXCX