# Setup
title: あーるのシレン2 TA日記
tagline: 現在の最果てへの道99FTA自己ベスト 1時間4分20秒 (世界6位)
baseurl: "https://riwn.github.io/my-shiren2/"
paginate: 1
locale: "ja"

# About/contact
author:
  name: あーる
  url: https://www.youtube.com/channel/UCaf0gShSdR6PeVqibl5TNJg

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
